[package]
name = "keymap"
version = "0.1.0"
authors = ["Samyak Bakliwal <w3bcode@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
lazy_static = "1.4"
prettytable-rs = "^0.8"
